---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: portfolio-test
spec:
  encryptedData:
    .dockerconfigjson: AgAXqSSPuPKKC4ncg1UXk/3aCdBQE3hePZplyRI3TZ4VH8PXznM4jVdqQWPwseMtiuKqgZU2oZWIs6j6qIAVhJab4jKBlC0avmDcPQVhXWUm+8O/pjxPFwYSiEfzCieMm9an/OjsfQTxA0Ml6Eja/Z0aQwphPGtg3zivdppYPtxcxxZRWfzbEOUforFGuVEMKOOgmfMtEp/6Z1KdLglbFA2WZFA/ZwRr0thcWYdaTPvrCJviyKNS66ov9hZhZ2cq7I7zd/EvbbR07aZlYtfU7ApXeQ4f0jbdaNJkd5D5pE+1pxF/3aGL5v+43hIn6AkpfWxihN+ce4SnP1Mb5ZrwgYqZ5c5XzmN7K7ZVPy/uJqwd0kFJkwxwb3tJzO4Tvn45d8XlClo3ouIYHulvWcv2vefwkQ4DIyrL6XzAZ71x9vYCFI1JEJat1wa65vXs9DUnybbgRkvANmK3yE3+Ws13+DQSw3mgcagQyyJlLl768A6PKk3CaQVDN3IkgsIBQ93VMJv0WP1JXxFnoMJcmcaZ5P524JEM1oQkKwn3SMef9Y/DazA+7Cj4oIVPugYKH2yk57DIjZz6eJVoyInAXRPlwWfYPedNIWb6qGSLRARFCbsnxRxsweTXV1eps8yaYaUPC7QUy4eS3JSWC5+jfCwjsLURckz3284CXqY9c6D3nJpYPCfIERFvpZ8JcEJbneuAw1/p1yEVFzZJb5oLInVhsSAHRlJEoHTM3KIlmA4ZeVKhKQXQ6GtVLGgx1APtqj39gsDSzI7E6pGZ1k11g+NxKSxgvJ5o0ce+R8r6LeNUlHofqBoOxqtH/j+qXfyhm/atvHTxPcDg7gKfqQmKkB8bbixbCR34UQ3SvrwLKPrjzmiB2o8UFfgNk5K1e2ZbEDlnOFKCMiboaKEnan0aPh9KPkK+CCGnmBNCAJUnszkDuwnYv3exfUxtREHObOl/gNFyFII=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: portfolio-test
    type: kubernetes.io/dockerconfigjson
