---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: inventory-test
spec:
  encryptedData:
    .dockerconfigjson: AgCwp79TbRbS5U/kFZatI25hVHhvh10uLB/iwXr7Z6tNt6CGOS962Yiy9HvipKm/vaRyK7ztlIVaP1GsNWSpAKfafu9wMXHIUUZTiBK7i+YpW+/HatxNW+8Kz7Le00Vo49whghfPtfXjcbrFz0899l0IIG9V27zUxo+coSC7sL3igmEGUvT2sk+2oNWxT+sVzGM+vJ5+bVOUHNN5B6cp5CCAA+zs74+ACJfVt6ABmSnFth5soTxL6gizsrdbrzPi/IGfbw7mqm74FKDIEqUUryWTwP2BcFEEWj2xBJIlIevjCxWEeXzhW8T1f+csPDuo/eDw4waSppJbwJIKTmG109LjPwKenz5H9jbjkQaTzuTCweGAKGCsi7NK96Mf/oBkOF2uQ3ECW/Xr+aH7NxFvJrpajG1Pu1XtpBXlzqC//jaeMj4WY70ud/G5rwV4lYMlTvWtunNTyPGBcGFMPQHY4xfdwe5RTZ1dN2rKaFsxCzXinjExjqtzv4UgQ2G4zggnocp5trCqHjOXdNKftulZ0t+biLxeHz8cmn7Kfjoxdz2XfmSsmSJR4q1+X0Ngg+BDfRzq1teabm3Oy7XvLDWwSCS+6T7mq43LJOhT6AChrrlNlAMhHyCB8Cyty+VZL6jYfBMjVXhtPOeSgOPvvEDD0BGthWE//lK0f9RTjQRDzSun+jVykHi9SeH+rQbAnphNhw5FNRDwLbaDavKzAO8FBVY1YPlFc2TgRWHereW3itSGi1GJKky1Khyn0GHxYufesFDaV0bbnNtxlc6HAqOo2eahyZ9oBN1tCl/HcjAW8jyN82aHjC6b9WQRbezkKGMwao0VgnznZSlp/MPkRVlkyt1BLRjM4+qM6DLoGYyVVz3ST5MLL+ZEE8vyPtqK53mhBaXp/8s/kvDx6kCWA1BAWLT2MK52ZIG0+i1rSsCHG9OtnLHkg86obo8natVJQlckYYk=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: inventory-test
    type: kubernetes.io/dockerconfigjson
