---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: portfolio
spec:
  encryptedData:
    .dockerconfigjson: AgCr+KJfcOxVOWgfay2lWwNI0+agX2gQkVef3fZOisddYd/qV0SC2sgms0HKgbTtWvaJQl/0X094H8iDjvsBraihEpspQBjxjGXMKWdQHt3IOVBPxZ6J4DBid7uV81487VAu9VHgahOr9FRSljLCT3ecSwTAS32SHE3btG0vMDsKEAQLy1eSgx/Dh7LeubwbdPkktPN7Q9MyTFvNBTFkgR82HrgxfAsIckBv7a1cE59eH9W3vr7By1qW3Fy2OBkfGdAYvhpPlH3DBIZtankVSmb1cfC8UfcLlu6goLlhcHHTRW9GcApJAzlRPezEfBMTQPHuelFLa77DhQUD3MF6tGFP76Q5BTlGx1tJsLazByOG2gQS+ejFTn/QVE1MOB2ViZw/9dPd8iLXps4gXqIHzT55vtIjk1flsuLlyvgxul2xj0Pl3DmLUVuLLbtepLAPIOuJAauZvD3vOy+aFXTwSGnDcXEADVX0EOWQ0pTsvgVCwCL5Qr3CnVlbpIoDyWQhBE66/MTbBlnLYNY3CWpdi6HIj4t14guEZO7RMPLQCLsPKnIR+WO0tRIpqjvHdWrXGMGf8R0QWfTyA1ld01Cze0tSkZX6GZfl5ZP84CHYUcRlEwxmmpRQ0Ms+vSyzJsM2WaK+cDtWM+zO5slEl5sbyUjKnuhpaHJee36ucziGLHCLdjq1YEwVUv43GHe/am+RoN3ZmuSv3MLIoZN2lTbPYKnBUptzJrS7tw9Jrys87j1DkXAoOsQBk14AuiTBDCc50KtT6eVFOUsOsTPaG6tkE8rcMNToaVLWaMv2dpAEwiv4l56gcojA3O9f2/vETAxAkJZ3NA6MeNn4vnrPspHxTClPGuinqXnczC7FP+GR6OEhltLxS6F6NObHoCDbHsDWmPQRRMxdNEhxOa6KMDl9csZ3pmutFccgkVhOAC/Tnz2fKzRXUTJ+TlU7HUdgGBd3YNU=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: portfolio
    type: kubernetes.io/dockerconfigjson
