---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: chat-test
spec:
  encryptedData:
    .dockerconfigjson: AgDJZ90VXD1GDLayiRDZ0Whu2d90ERnAdws90eL+qEah18pAp0fhIb386CimA//9DHL0VzMQU2lFQFyG6HWjHmW0I0Ehb7V1nBj5U7sgSp+2WPrf+aO7Ad247KWHv+cHvt31y0gqPPj4MsMbiWfYQwVW0JEXA+2DvcTMQNrzg4OW906n/aqN5La53sAp6rRr5p+8wSzfqUjo4IAWU6KNGTaN0c2RrkgEd6odKAglj+aFwB59j69uNtG9+TOBh1cYNrWMeqhJtoEIgo//x6LpnltK1fmCTMFXuAJ4xX4AD2VU2PaBdfyR/P19NRiMZdTQpGawCpAOvsyfLNVrcfipXz9kh+E0vAiQk2sJba9tCyDOL3/dKWCMnQDQo0K/FOfCEQMmIG/LaPd/Y3nK/kr7CSb76uYdZaPR9pAAfM30ZYqjZQnoraxeqvpWSY4HxxRM5SHKdF7GlwLVAkqyyXdtak1KAHBxivIEx02n3j3kV3EdBhoavgsVXMq2rGo1IOs+ZGw2vql8tt9QuxK4aUCVP8IJ2PHyuGMfBOXfNDrWt3mHj6iaPMY7Wov5EycQT1L6O4zlp2uhERLvy9Q4dVctBos55ztBfRY7jumZLYb/eA9oiGp8mpn1BqsHEt1LR+1faj5XEwwolrUo8QRBCfk88nlJOy358qKiL4MKgaK7A5x+w8dkAaHtvt5xnKQttIaHwyAxsnMxhwmYpuyrqTaVygkw8M5pwZ+j/BijHio+QVKlrizZIPkKjZJcgTkGb7h6SYXOh955vpnzpz65G4V3whYuy6vcq/sUxfpW5aEF9DGvnNCWc8QgtGqpVX1fOY0+NdKwqYM/aswiNexu0YlZivOxYgS07dtEiV7B+XB72mxnpPyn4nxcMf/I3YbKc8NpIhtfidhT79tFXT4P/4/JgRJupu+VtArRJpPd7yVycUfvsrvuLJdbgXw2R1npF4bXY9w=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: chat-test
    type: kubernetes.io/dockerconfigjson
