---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: home-test
spec:
  encryptedData:
    .dockerconfigjson: AgBPyAhUNvZLP1ZxZR3EAlWMKVX50uzylfJ2dQWrwfYTYKiCFpsdtsSrlgrNqMyaynsotY6SADJv/1EVytmhN8ywqy7l9LZmLHFQuwLf9In11cyBZdMBvnAcTGVeLEKdhqMySOeer5Zyuum6I0BarK29tzu9mMRqEUkclXtjINiSzXyx8UDwaeRAD98T4KZM+9CxA8EGxy3Bn4+mJxf3yrwBTI7Ab1RYNL0qCJ9DV2Z0OWa3D4gAE5f/ifkm71BL4w+wE6Zio+64kd+39tsgSVFcmlKw837aERVHb31tgsFeUyr1mnk3SYEWNAUvCfEHJFyW8M6X+h2425S03UwgAigmsnVYret3P8NV1ww19chHbkbiUM9pQp9YXv6YFS8NCHRtSPk1XK7K4tRb+kT6mSxOUaqyDgRyTGoYHBpohdqX2YRlDb/MUeyD0Q6lsugWl8vWNp3SI2TANvQgEm9AEaaAy0DtAx7sbhCF7zG/mGDtVLke/YaA1TDQGKDBqV2/P2N47/plNowswwIT0sWoPRqigrg1z50DobaS2q5rXDqyKK4oOX++LNDNAcqHHG2kq0bzmBDIt3YA75Ezkf+aDR+TEVks4Fmv34jDHmEW5EUMiscJ+TPGusSv41ad6cU02RhvuaAs8X9wBvsl6FpnIHmlFN39nLFitEuKUwirComna4bvkJeqjlMYaNlGQ5LYDKR/uivL4GPiGwes0Cz12JotuOwpoUd0nmw13P3gD0yUP0cVyYiMNd/jf9U8id42KFQrMENJHC9mrgAp55fXG/aPOS3xHPhBbJiOt4uFPsqaIWToI5ENfXeixxfil5IC4K3r1I76wwbE0oxHenRltRA09HiF5E8zoayOKJk7tPFrpM7cSiQ2WIDdjRUOavwRGzOTVoxQJEQLd8GTU4HhHQ5kLt8MRoDcyvdyzDQ7KcHAmVYZP8im16VIIJNIjI8Z+MY=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: home-test
    type: kubernetes.io/dockerconfigjson
