---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fincontrol-test
spec:
  encryptedData:
    .dockerconfigjson: AgB1hCS22YYezD3ERKbuG5FSRGX/RCDLOE+000YS4poVCxU8anfBzfDdFkGNADO1F6pk9jGwaJLgW+ntvtYKlgJHT+I3xqa34MqScLAJQwtRDeqo3G3FPGnhrtSnwZ5B2duTnOUrcfyomc9Msdcqzid7YSEe62S3U5fBnsA1Yz3fJit3l2lVrnCv6w+9ozFd5HY++NGUe7jH18Je0biT+HS+K0WXd/L4KdXHreT49H3BUAVwj6dr+4uWZuF82ePE+t7kZfJhDHajpauwl6Nuu9P4pVRKN0XvWFTHe7E88ysmxU7WYlmFs74MCMwcACBVP07BQeiyPXSqajOfYwhLie7W3/gZxNJPxT0jRKWRCIKcjyLZHqdvslwI/zQnBOSKPZIdQH5565wKyCv+7K7LminXngSn0V5K/9LfmRiUsniA20YY9gF9KgwZ6vDnvyuNoB9BeRgaahm33RRnQ1mIUVLw388BWwrytBu7WB+2NVBbnOQC11dfQmtD6vRWEig9PaEAKtOaybiQ+nO8TxJiGri+wfTT5MxDrT1MRaTJHVBr916kjdOFDN/QiEYUh8BCvhvsFWx28aah4b3qHE0/2o/bN3sRc10Xa9xHZzyJHZ6f/vmHbQlv5/qEQbXQKV1Xo3eRmVTxQS0j7h2sjRHryWUXT+jpfvakGCQjtwmj8Pbkoyayz7y12xyzzoVz0TylFEYStzkbqw4/Dbr1PVEFFcUF59nv5UTmSfb9Vjza3zh4okyt3PvH1Hr3P41qgk/oKr5BGNzXxhZTM9Uv/GvGNISiNQXaj+34ObAnXZ7LNw5ZC6Kouu9d+kFf2unAzZhPzSklyL4l0RwLkmEgf3N2bBMSWvYSA7H+imYfsi0Tr8IBfrZNLJSWzzFIHNk8D+4svi2y6UjGTy4040APCqsLUK22u+zunqZiux8jwn0darOO5JdCWzmnTlUB1Ocx9bzzHFE=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fincontrol-test
    type: kubernetes.io/dockerconfigjson
