---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: compra
spec:
  encryptedData:
    .dockerconfigjson: AgBY+4cgrqUauh1H/Nb7mYkEWQDNMixxR7VPbBSXF3QEuWCiEA8LaH/LYK1PoBa5XSTyje/ZomBlE+MaYlWXxOoViszTnOCCqQiJ7QIKefDHuNuRObxWY2UNc95nrxH2WzQLb/ssmquBdIwMA2DJjMEujfgQStAs7lD7QfumLdS5Ve4RV4frQ0gcaAkueRUUnZipbE8QJeG4wer9sLb2vex8ZcHgyOfKvENyxkzuepkqzOtu7qxgiIBY7h0eDrHUZ5G7bdvyO93V6FapWqFGgQAtYrX05/aUbzZiCQptcf8SbdtfKq5Me5RTheEEtTLfrilZ5PIW9ZEvi2STVNqwACJteB/T16H5CE6XrFycnxz/ZPprzTXnFjsXFdbC9F+jNbiC2bnOzKeGzgrjsHD1bnS98qSLIFDucYXwYG1kiWUt/4ImC/m63hul37fddsfUCTqS7bE2Ca9Nhhd07/+zVsWyWFiFlFz3PRk1CaXjROFju3ds7fdnx+n6PjpNTh6k9/DTp2ujy8TQpVJIGLDEJSzTDwfjQeW+JMLh96Lo4UoHa0HDHNxUT3MBwByKidFLE3oeeb5QHeYhAXWk6MLUJpAa//Y27umwuAzT9APTWo7Cp47bLuAxPiSWo0UcZi8ikdFStBlPK8bNEQXCFZi6w4O1oPFEoQfowSd/ZStEYifhHfTdSMs0zK5vsF3UIgZNe0bw8NdW8vVv7jYx8cJps6hglao91yCG36j5kiz1k30PGpELVkxxbblsaHIMXXW5F54ixSfZI2B5P08u3/Zs5D+hLRUZ4/GWuLNmohTD0f6OEABJaIfImYXDm/S7pNMzVw6fGKkDPYHpnvaeGa7SVsCgbJtpBrlAAnEHro5VOPPWImOGIHIeUHvxYKRPG7yy3VGcVCzePIVaRVgIGWmSQ4O4EyTBJtAzuR/33L5SjyGlnhMDv19fjJqTDGfUulX1xjg=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: compra
    type: kubernetes.io/dockerconfigjson
