---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: blog-test
spec:
  encryptedData:
    .dockerconfigjson: AgBBCNAUBrkmz1DAqvLHeTGV1DPerp725h1sznxXmxL8xs4sw5jxcQDpeBltaR7H6lIQz9vMzgxC4vZTLUr7vTp36sL8B5yIJ3QcVf+SOCdD3aFxF2nIkpbKGmLld8zN32KRSL01tXpMCjhB1nnB+V1VXAUwrljVfj4y+vBfkwEg8dOJsfs/jIQk78aZVOzv8e7G+u+kqQ77Y3BvElEwEhpYccxN0FKu2BKlJjlIimTfA3LF8TQMobxGcUO2A61jNDlKvcKMnaYKbSa36/mFlxKg747eEADXDZLvkptYqfjEmehaur33s5YT51CevyFU3ksGQWC2oyRZfTDMGFOD4YN4Fo6cgEC6Aw2j2C2A6NxU8pq3RdnOlBBCEWOXFB2vBvlRqCk5fK5wRLIMQE7EsldAdamZe4Hq3v3vjm71lZNkBEWbNAnIn/ZwadXEPlzetxizT4/g2cnkTRUoZriTwPFgKaXPB5LCd8EdG+vKajckmAAmd+BWXXK3mYFXsfvhAyrgi3H9J+59CPUtHZ2FUyNmeIsLP/sweCAXKAtroe5ae9AXy/EqiNH0OkVMEqDR9w2aPU7trVYejLj0pBL8k7i0LhBWO+mD3j6LMl7k8t3B86BpEltjWWjI5AX+oRQGT1BjZBJwJTsjl3onskI0rRgRXzZSakLAe93qYNzI5Jn2v7io6JC5MezpyfKFx7i1xL/ZRc9+0V1UOnceOA3PL7sXR5AlJlSvuF1KGpv3k82Zy45qlQOEGxj4Eo81d5WRiLI/xcwPcrFWWLVs82Oc6TavBjpFXLghubiCICqVy/vR1EpjBDPVCYOWWtOvDI6Ptbrs+8hvwH29KAMNqmf7Ct8UH6N+UDCs824Pz5HWyccKTQ/rsU1kQ3EMepVo6qoUOtamfaos3vd/4z0NgjeqJZzIfYoHlGpgCejk/DzMYAaf3NThUcPEN3ONzg07b3FPq4A=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: blog-test
    type: kubernetes.io/dockerconfigjson
