---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: home
spec:
  encryptedData:
    .dockerconfigjson: AgCIk6/yMXTfuyl29AtP8If9CLn4rcnfoDgqvhGni6XbtnDYxIDoH/GmeBDEIWnkOayaLdEQZA0DRW4Uz7XU2nRLVEhVY7OHdwMudVydf8lf/jfGL7jMMcuDYSZ6AZdsF5XBHY+/RW0vX9BC4x4u7Gs3seKrppbXq4Q47JSZfvsrBLIBQ6ERptBnPP7GvgyI/GHBPW85c43nz/1qGjQvpBarXsPKcfMlZfrZd5S4evo+Redbz29U0wvIp4ZUWx72rXNN2fg3pXLUoou+Wy7+cJElwDkHCv8DAPUIRgvNAR3v69P2hvCt3lEkzDKFZmxoLAfbPl++OZRL4B7jw3WtijGLV7EY6ggVTWOW37FaVj41O90P39sWvw11ZYTIpY7vxhor7mulJH+u8UV4rbZn5L+TLCsG336/K9nqqzO3TqaizT7sYqwG9s8maWgICAePJ22Ni2J6+I/gRi/aK22u5RfYCwg0IubDkf5zsMjqtN3Rrsnu53yiDazlNdidMeqvYiAHyzBY4ecCLoE70C8MXyp1joEP3wePAevUkixPmKG/BPsW1pvHDAdDPPyp08AY32UIUTa5oy0PD0PNOCdEsVbu3qTqDjmZov/MoAt76yco0YLFAvM42ctsI3uEvTap1mJWirR4qNo/u/XDeFqanYmTUjVi56ibaj/d3OgpuF22xlHUxHR8oO4hoa4PLnhq9UxQiJi9gb6nveTpup85u/NQFia2WIH3t0Hl9X3zdtdzJhZcSAK+lXQnffsCsgaQKmoKzJcJQyCLA2y4Zs+lG/csjfffuLtGakC0MMjrS7rH0wK0MBedDtZWyetN/IaeMyOE4oht6uLJZSDl3/fxGD3ykY9CsUAZSZeUV/rCkgy7nHEwF67v0UwiuZWuzI82l52gUpf0b+BDnJLm4qY3ROmfDwQyWN4RLCq6ftvz2HQ16tGu5bsrgaTIyhQ/TVt6O5g=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: home
    type: kubernetes.io/dockerconfigjson
