---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: blog
spec:
  encryptedData:
    .dockerconfigjson: AgBsk4tCpWa4Z4Z9at7Iz6yCCiR0BgY5tp5zvICMDc5D6OY7jUgFIkFav0yPhhMrlPpTVFHSuDEuJAC++Ef6SfrvhmdCImrc81WDTZJCc1e36EvUfO0sZ7593P6NAn1/lc3i09rVYfYjaAxfzx/Hhn4xbccbBR+LeaIxiB2wbkj03CgsIIL3ioMjI5My3Y6ZfgbrorUJ+EeT3PVGt7ftDqxvLubK4/fnvvBHRXmdSncglcfbWFaWeOjjDSmxp+nZofFfvY3dtzQ5VXvcEcDrRWGOxaGVC2eaKEAy3c9yDJ6hIC7hwsq9fCoTA6yzSo/sZp9KKD6Mam+mjQIrUIMH81vVXjSNfaE+kLrYDoMzSaLAhNLVb9KN53Pwr4fSQBNbY1egqGXxsD3HpQ31or3poXmVkaz8R+yIGZ2kDIQeBOKjqGj/P4+m97Y6dcuQ5tEdjQMl4a1LTk7+ztwFqDrLVkrZvx8TxJzkUSv2X6VAK9MnLk6mhcH9GfChodOBDul+fg2ycjjb89SlFIaPDLAR20SaEmVxWK9Zy/jo5kT1hjn1K2HeRN1/iYeshLY82+h8hAtwy7RWlKpYSP8ZYggsj2dx53BN0Ovgj99iApTXryVNWwobrvplg8DArSBbF5sIcwSUp7CfYHrYIe6mib9RHUzV09XxJZtiu2EvqjCwiyE1RCPZY0XMchBX83OpryEtuKYTZXRq2eSTg8OXDM9phJEd5MKXBaZ6tvDwRY/2/D/BlPSKcafZrTdCA2XeT/NUs6M4we3RCn0AR5mRUFjM4EtmQaStcsxXGqMu1IFPIMXb8pKXAUX/2Ljaw8AEOTB+z/GXmpyxjdNa/eEwXo4jEHlNoP9itGR9XVElB+e5OAWxflXoI8Ix5J8j5fonoQn9Hn2uviRWWrQ+szviLWDE8WHeZ1klYyKXkwNft1ozE4Puv4VLLmvK+BJ4g4iTrOR8JII=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: blog
    type: kubernetes.io/dockerconfigjson
