---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: inventory
spec:
  encryptedData:
    .dockerconfigjson: AgCKn950m1EaP9C5UM51EDWqf+ZVV2gM9tudVvpgM/A1V59mvDvxFhkVKEcmeNxu7AtY1Vu/U1bSAu8bFSkNgkrGZTGq75AC8wdEOTkTfCKzcWNn1gTuNYv6mb5SgNWdSVAsO6LlmJMELu+htu1RE68E+Lx4RhPPsTvcTSyM9THUdvGAfnueNCbvXW8PUOKhfrObgCC71dV19zLofCmGqF3Lzalenpn0laiLuBFqwRbXHOhtdhYJ7NuS4wFZZ8W06ZYYqXGz6/r3Zj3aAOXauI3sacgBBMjzlxFZPauiGG9M8E+aaYOckP0QXzRkz2MurX5GPmyIovkjbcEtABAdlmhYJYhBmtlSd3jbvfh9rqFyKJRv6litv5oH+NBj50yoDKIWSve34i8RI0ev8mXUdl+xeOOm6R0boH2x79U5VVySg6MSmcR7N0GwoL/mqL3PHPqq8fOMyQdBSPM9XfZyMa+sB9ogm/hDeBCZqJaM1M4M4chcu4c65cSdIQr/DL5cvNLNPzIPGtuz/K7OfjcrDY3CFGUxrrLp5H45DapIt0EoIrX2Oc07NxJlUGx3viyvCFQltSaDDUu7y6yXlcNYhrQyq7sNYBvo1d+6blw4legfSO/8+8yp9TvGY+s3IGOsk8cTdieJ1qYX8tGBONXeyq2UT1rjRv3meUc5Z18Oki3A6CY+1DbtSqdrvXLAlDGLczL9IjWqfw0SL0/jmQaFfqgFQ5PtVcU7NiHcCtjbljUksVIgqu7bXIMeM+xRd45fIR45rjfLJlTKefax6+DToxtpCN/jEg6tGx539ifvlYE6S6cMujPnb6HBndQxsFIzebhW4C1EckHEw22Yt/GPHduSIj/0WTPslEra2QcDb3RjvjasXCw7ItquFK+BKd/6GQxij1bsqp4H9xbBP7Z+v3CpqiRkwg7IKwE2Xp6Mc4K43r26M7pYWbKkCoSuZmWWrDA=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: inventory
    type: kubernetes.io/dockerconfigjson
