---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fincontrol
spec:
  encryptedData:
    .dockerconfigjson: AgC/4Lfz65LxSZDxfE92jFPzZRSCmDgDm7wpCEcZuM4zqrmKEa8G9jvJ8WudVbJatL0DYTeg36byaNDwlOmDk3gu6GZo39FBNbAD9pXj1KqkqIACEo1Jfo8oSfczt/Doc6FVqyfKf0TdzZxMPxQFd8qxLjBkJHEA5YfpgiaBOK15sv2eDeKUpQWoAgL2McCVW0RD4FbGuZLKkTP/djNCuctbBc3OlPd9eJYG+67jeSMG9bhYQc9xwOsT8vXBvaGUnszwpRxKxq2HfwD6MYnb17yv86hg3PrUzQcQPBaBB/Frzl9evCKAD+uvQgdbvbAAehYPPwJYLfgcBa7e/tp2Sja5Otqq6AR07vwxEye+xXUsYXuJy1Tvv46MF1iMaajI659dRg23GEOnO1BmWqGzFU3pJo60D5ttKBikgZ+2NKV+ij4qcCWVsk/xO7Y4luHqBxG0tGE1ka90YjTWAWR2EDN7gHL28Vx45nc9CH6zeiKrNzMMzPv+wug7vhw4F6IaV6k22gf8/WucE7dpkySJ98XghA91qoF+NC8Rm7HAtZRbY448LDjDLZ7qN23kaOiJ4wWHPFX00ry/3Y019vXk/LeFkDjhMg+wYjNUCSaJ4SXLx79XYNerC2vGE3qfyGksbnX7WehT6WRV7Z8uSAVFyYelTgg9I59Upgcnvuf4dMXIb+rveBC9bsJv9Op03KNGQEVI/cggWShwsKD3liNVwDyjWteB/Uu2dsKyMNNz2w8/bezSc1kKhjBntJsCGT6P3xaknSURwhjubvlaO/Cv+1InpudHq+1kMrEBfeBKlIOXzOMIjd3O1wJqH6pl/sZkTWISPc2gTzK0ds/S3YVpjAlh27Fz/ReXd07/AlVhymC/0zqL9hU9mRPRCvLmROBg2xGBUxQeQ0/7yrwzBdrcbyDhY1sCSbGSd1JeY+69mMtrnCarPtk48sAhjwTQyuPR/XA=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fincontrol
    type: kubernetes.io/dockerconfigjson
