---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: chat
spec:
  encryptedData:
    .dockerconfigjson: AgBk4v3K7LbgnDE+K2jW4bVg7VBRVLbF5X4HvG4WsWBFWcuUVvOtcj3ZtjdBbCfQ5LG3+pVh6acctbL4q/qK9UEHVikl6V4z7OuB7jKkyF84H4k6bw7HLsJiEfvFlz7zqyGekLcVKwN2Gg8Kco+GQdqFRNTGxA3V+pmgwpQlGoCYidsowitH3rFCtBlZlq4o+rut3L/Ga4lSemmYN7nM+zaWRI3MRavGuPhtmsVl+IaSKoRODVhByQLrSbDICEPCCRvzK6MT+fUXggnXi/looXilZK5TSpZr7Jzr41b7F9+EYFDwsPUKS4RKdKphnuRZs/12lvv9GIWBNiO8qHo2C/VmIqCOQoh8L+C7mFKiUueA0OeZe2wNDvpVNcJhe2lyBnufPq57hutkIhHX7Sd4lIb6kV71h224glQfOOA4/eSf4evfPxRXg8k27cU2JZqkZLHhyODplv3hV6G55MFnek/w85y0VBoRQxGNbGFKpSbw6W46ONXD6yXX85ETgEjZ1IgA5m0gV+2RkjGd2AmtQlICJwjsCUtkm0xLHnDngKa0Ed+vDBhv6Rr40jyRo7Ocg3laky1Nn1K8sI6UHiX03x4LgZ/Jd/2lwue6+EgZj3j8mUSqLW+UjmxU+NYu3+Y0rqDQ8dmO8dO16h33n/gDasf6i4Q0WKzlfk94aBonqGvGY4k7+U7UcQ7BovvdygQ/M2kaOor4igET9fNeJUeMxIjXOFL+HIqxi9LSI/DJ4N6dAFHVeEMEavH4RwxtW7wfVQLx8u1xp176uk3TLgbvGE0Y+BwsTvVajOwTPaR8SA7Z3kkSi7RavtzQxKnspMmfl+9VDsn6oxlT7HYm6hlXM90I/1KBIUALZ1xU976vrueeFs90ku4B3jJ0k3J3v5UeaFiI4IoO/ZDtlQJKN1Sfusr3rUVwxPwvEAvT8mIlDnQOWwnayRGY2GGMdnFgF8xNksE=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: chat
    type: kubernetes.io/dockerconfigjson
