---
extends: default

rules:
  line-length:
    max: 160
    level: warning
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

yaml-files:
  - '*.yaml'
  - '*.yml'
  # Explicitly NOT linting .json files
