---
# k3d / k3s
k3d_version: "v5.7.4"
k3s_version: "v1.31.5+k3s1"
k3d_cluster_name: "jcrlabs"

# Tools
helm_version: "v3.17.0"
kubectl_version: "v1.31.5"

# ArgoCD
argocd_version: "v2.14.0"

# Sealed Secrets
sealed_secrets_version: "v0.28.0"

# Domain
base_domain: "jcrlabs.net"

# cert-manager — ya instalado en el cluster, no re-crear
# ClusterIssuer existente : letsencrypt-cloudflare
# Wildcard cert existente : wildcard-jcrlabs  →  secret: wildcard-jcrlabs-tls
