apiVersion: apps/v1
kind: Deployment
metadata:
  name: redkey-operator
  namespace: redkey-system
  labels:
    control-plane: redkey-operator
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      control-plane: redkey-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: redkey-operator
    spec:
      securityContext:
        runAsNonRoot: true
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: redkey-operator
          image: ghcr.io/jcrlabs/redkey-operator:0.1.0
          imagePullPolicy: Always
          command:
            - /manager
          args:
            - --leader-elect
            - --max-concurrent-reconciles
            - "10"
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
      serviceAccountName: redkey-operator-sa
      terminationGracePeriodSeconds: 10
