# Wildcard certificate for *.jcrlabs.net (production)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-jcrlabs-net
  namespace: cert-manager
spec:
  secretName: wildcard-jcrlabs-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.jcrlabs.net"
    - "jcrlabs.net"
