---
- name: Install Calico CNI
  hosts: control_plane
  become: false
  tasks:
    - name: Apply Calico manifest
      command: kubectl apply -f {{ calico_manifest_url }}
      environment:
        KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
      register: calico_result
      changed_when: "'created' in calico_result.stdout or 'configured' in calico_result.stdout"

    - name: Wait for all nodes to be Ready
      command: kubectl get nodes --no-headers
      environment:
        KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
      register: nodes_status
      until: nodes_status.stdout_lines | select('search', 'NotReady') | list | length == 0
      retries: 20
      delay: 15
      changed_when: false
