apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/portfolio.yaml
  - applicationsets/portfolio-apps-prod.yaml
  - applicationsets/portfolio-apps-test.yaml
  - applicationsets/infra-apps.yaml
