apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - root-app.yaml
  - projects/portfolio.yaml
  - applicationsets/portfolio-apps-prod.yaml
  - applicationsets/infra-apps.yaml
  - applications/portfolio-gateway-prod.yaml
  - applications/portfolio-landing-prod.yaml
  - applications/blog-back-prod.yaml
  - applications/blog-front-prod.yaml
  - applications/blog-mongodb-prod.yaml
  - applications/inventory-back-prod.yaml
  - applications/inventory-front-prod.yaml
  - applications/fincontrol-back-prod.yaml
  - applications/fincontrol-front-prod.yaml
  - applications/chat-back-prod.yaml
  - applications/chat-front-prod.yaml
  - applications/sealed-secrets.yaml
