apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/portfolio.yaml
  - applicationsets/portfolio-apps-prod.yaml
  - applicationsets/portfolio-apps-test.yaml
  - applicationsets/infra-apps.yaml
  - applications/portfolio-gateway-prod.yaml
  - applications/portfolio-gateway-test.yaml
  - applications/portfolio-landing-prod.yaml
  - applications/portfolio-landing-test.yaml
  - applications/blog-back-prod.yaml
  - applications/blog-back-test.yaml
  - applications/blog-front-prod.yaml
  - applications/blog-front-test.yaml
  - applications/blog-mongodb-prod.yaml
  - applications/blog-mongodb-test.yaml
