apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-back-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: portfolio
  source:
    repoURL: https://github.com/jcrlabs/blog-back.git
    targetRevision: develop
    path: deploy/helm
    helm:
      valueFiles:
        - values.yaml
        - values-test.yaml
      parameters:
        - name: secretName
          value: blog-back-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
