apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redkey-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jcrlabs/jcrlabs-infra.git
    targetRevision: main
    path: k8s/redkey-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: redkey-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
